### ISSUE TITLE
Running Mochify with PhantomJS -flag causes 'Bad Argument' -error

### ISSUE THREAD

**Issue by pyryjook** [mantoni/mochify.js#81]
I'm running mochify thru API, like this:

```
  mochify(path.join(serviceDir, serviceName, 'tests/client-tests/**/*.js'), {
    reporter : 'spec',
    cover    : true,
    phantomjs: true
  }).bundle();
```
It results this error:
```
child_process.js:946
  var r = this._handle.spawn(options);
                       ^
TypeError: Bad argument
    at ChildProcess.spawn (child_process.js:946:24)
    at Object.exports.spawn (child_process.js:746:9)
    at spawn (/my-project/node_modules/mochify/node_modules/phantomic/node_modules/cross-spawn/index.js:87:19)
    at launchPhantom (/my-project/node_modules/mochify/node_modules/phantomic/lib/phantomic.js:60:19)
    at /my-project/node_modules/mochify/node_modules/phantomic/lib/phantomic.js:136:7
    at Server.<anonymous> (/my-project/node_modules/mochify/node_modules/phantomic/lib/phantomic.js:37:5)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1056:10
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
```

If I do not add the phantomjs-flag, everything works as expected.
I also have installed PhantomJS on my machine and it works also as expected.

Any ideas what is going on with this? Thanks!

EDIT:

I'm running on OSX 10.10.2

**Comment by pyryjook** [comment]
Oh, now I realised. It works as expected, if my phantomJS is not in $PATH i should use parameter 'phantomjs' and it should be bath, not boolean in any case.

My bad.
